global:
  scrape_interval:     2s # How often to collect metrics
  evaluation_interval: 2s # How often to evaluate rules for aggregation and alerting

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "server_starter"
    static_configs:
      - targets: [ "host.docker.internal:2112" ]
