app:
    is_production: false
    name: "SSO"
    log_level: "debug"                    # debug, info, warn, error, panic, fatal
    tim_to_confirm_registration: 24h    # сколько времени выделяем для регистрации
server:
    port: 3001
db:
    ssl_mode: "disable"
    min_conn: 1
    max_conn: 20

watch:
    name: "ZAKON3"
