app:
    is_production: true
    name: "SSO"
    log_level: "info"                    # debug, info, warn, error, panic, fatal
server:
    port: 3001
db:
    ssl_mode: "disable"
    min_conn: 5
    max_conn: 20

watch:
    name: "ZAKON PRO1"
